### ISSUE TITLE
Not all Box Names when fetched using the new AlgorandClient class should have utf-8 decoding attempted

### ISSUE THREAD

**Issue by atsoc1993** [algorandfoundation/algokit-utils-py#148]
When fetching box names using the new AlgorandClient class it'll attempt to utf-8 decode the box name, but not all box name schemas will successfully utf-8 decode:

```
from constants import algorand, app_id

boxes = algorand.app.get_box_names(app_id)

for box in boxes:
    print(box)
```

```Traceback (most recent call last):
  File "c:\Users\atsoc\OneDrive\Desktop\NFT Marketplace\2_check_listings.py", line 3, in <module>
    boxes = algorand.app.get_box_names(app_id)
  File "c:\Users\atsoc\AppData\Local\Programs\Python\Python313\Lib\site-packages\algokit_utils\applications\app_manager.py", line 279, in get_box_names
    name=base64.b64decode(b["name"]).decode("utf-8"),
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 2: invalid start byte```


## Solution

I supposed a quick fix would be to "try" to utf-8 decode the box name, and if it fails just use a None Type?
For testing, I will leave an application ID on testnet with a singular box that replicates this error: 735880029

# Original

```    def get_box_names(self, app_id: int) -> list[BoxName]:
        """Get names of all boxes for an application.

        :param app_id: The application ID
        :return: List of box names

        :example:
            >>> app_manager = AppManager(algod_client)
            >>> app_id = 123
            >>> box_names = app_manager.get_box_names(app_id)
        """

        box_result = self._algod.application_boxes(app_id)
        assert isinstance(box_result, dict)
        return [
            BoxName(
                name_raw=base64.b64decode(b["name"]),
                name_base64=b["name"],
                name=base64.b64decode(b["name"]).decode("utf-8"),
            )
            for b in box_result["boxes"]
        ]```

# Corrected

```    def get_box_names(self, app_id: int) -> list[BoxName]:
        """Get names of all boxes for an application.

        :param app_id: The application ID
        :return: List of box names

        :example:
            >>> app_manager = AppManager(algod_client)
            >>> app_id = 123
            >>> box_names = app_manager.get_box_names(app_id)
        """

        box_result = self._algod.application_boxes(app_id)
        assert isinstance(box_result, dict)
        try:
            name=base64.b64decode(b["name"]).decode("utf-8")
        except:
            name=None
        return [
            BoxName(
                name_raw=base64.b64decode(b["name"]),
                name_base64=b["name"],
                name=name,
            )
            for b in box_result["boxes"]
        ]```

## Algokit Doctor Output:
```timestamp: 2025-03-17T15:37:52+00:00
AlgoKit: 2.5.2
AlgoKit Python: 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] (location: C:\Users\atsoc\AppData\Local\Programs\Python\Python313)
OS: Windows-11-10.0.26100-SP0
docker: 27.4.0
docker compose: 2.31.0-desktop.2
git: 2.47.1.windows.2
python: 3.13.1 (location: C:\Users\atsoc\AppData\Local\Programs\Python\Python313\python.EXE)
python3: Command not found!
pipx: 1.7.1
poetry: 2.0.1
node: 22.13.1
npm: 10.9.2
winget: 1.10.340```

**Comment by CiottiGiorgio** [comment]
Thanks for raising this issue. Let me look into it.

**Comment by lempira** [comment]
This has been fixed in #153

**Comment by atsoc1993** [comment]
> This has been fixed in [#153](https://github.com/algorandfoundation/algokit-utils-py/pull/153)

Hello Lempira— so sorry but I'm still having the same issue after updating:

```
ownloading algokit_utils-4.0.1-py3-none-any.whl (158 kB)
Installing collected packages: algokit_utils
  Attempting uninstall: algokit_utils
    Found existing installation: algokit-utils 4.0.0
    Uninstalling algokit-utils-4.0.0:
      Successfully uninstalled algokit-utils-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
algokit 2.6.2 requires algokit-utils<4.0.0,>=3.0.0, but you have algokit-utils 4.0.1 which is incompatible.
Successfully installed algokit_utils-4.0.1

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\atsoc\OneDrive\Desktop\ALGO.FUN>  c:; cd 'c:\Users\atsoc\OneDrive\Desktop\ALGO.FUN'; & 'c:\Users\atsoc\AppData\Local\Programs\Python\Python313\python.exe' 'c:\Users\atsoc\.vscode\extensions\ms-python.debugpy-2025.6.0-win32-x64\bundled\libs\debugpy\launcher' '60657' '--' 'c:\Users\atsoc\OneDrive\Desktop\ALGO.FUN\contracts\AlgofunBondingCurve\5_sell.py' 
Traceback (most recent call last):
  File "c:\Users\atsoc\AppData\Local\Programs\Python\Python313\Lib\site-packages\algokit_utils\applications\app_manager.py", line 348, in get_box_value_from_abi_type
    decoded_value = abi_type.decode(value)
  File "c:\Users\atsoc\AppData\Local\Programs\Python\Python313\Lib\site-packages\algosdk\abi\tuple_type.py", line 305, in decode
    raise error.ABIEncodingError(
        f"input string was not fully consumed: {bytestring!r}"
    )
algosdk.error.ABIEncodingError: input string was not fully consumed: b'\x00\x00\x00\x00\x00\x00\xc4\xfb\x00\x00\x00\x00h\x1c\x07\x9d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\xff\xee\xc6\x05;[\xe98\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\atsoc\OneDrive\Desktop\ALGO.FUN\contracts\AlgofunBondingCurve\5_sell.py", line 26, in <module>
    amount_held, last_purchase_time, last_cumulative_reward, anti_snipe_delay_active = algorand.app.get_box_value_from_abi_type(app_id=token_app_id, box_name=address_decoded, abi_type=user_holdings_coder)
                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\atsoc\AppData\Local\Programs\Python\Python313\Lib\site-packages\algokit_utils\applications\app_manager.py", line 351, in get_box_value_from_abi_type
    raise ValueError(f"Failed to decode box value {value.decode('utf-8')} with ABI type {abi_type}") from e
                                                   ~~~~~~~~~~~~^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 6: invalid continuation byte
```
